/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#80d5cb',
        primary: '#005c55',
        'on-tertiary-fixed-variant': '#005236',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cbdbf5',
        'surface-tint': '#006a63',
        outline: '#6e7977',
        'on-primary-fixed-variant': '#00504a',
        'surface-container-high': '#dce9ff',
        'on-secondary-container': '#684000',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#9cf2e8',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'secondary-container': '#fea619',
        'on-primary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'inverse-on-surface': '#eaf1ff',
        surface: '#f8f9ff',
        'tertiary-fixed': '#6ffbbe',
        error: '#ba1a1a',
        'surface-container-low': '#eff4ff',
        'on-primary-container': '#a3faef',
        secondary: '#855300',
        'on-tertiary-fixed': '#002113',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ffddb8',
        tertiary: '#005e3f',
        'on-secondary-fixed-variant': '#653e00',
        'on-background': '#0b1c30',
        'on-surface-variant': '#3e4947',
        'on-tertiary-container': '#99ffcd',
        'on-primary-fixed': '#00201d',
        'secondary-fixed-dim': '#ffb95f',
        'primary-fixed-dim': '#80d5cb',
        'outline-variant': '#bdc9c6',
        'on-secondary-fixed': '#2a1700',
        'tertiary-container': '#007952',
        'primary-container': '#0f766e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        gutter: '24px',
        xl: '32px',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-base': ['Inter', 'IBM Plex Sans Arabic', 'sans-serif'],
        'body-sm': ['Inter', 'IBM Plex Sans Arabic', 'sans-serif'],
        'display-lg': ['Inter', 'IBM Plex Sans Arabic', 'sans-serif'],
        'headline-md': ['Inter', 'IBM Plex Sans Arabic', 'sans-serif'],
        'label-md': ['Inter', 'IBM Plex Sans Arabic', 'sans-serif'],
        'title-lg': ['Inter', 'IBM Plex Sans Arabic', 'sans-serif'],
      },
      fontSize: {
        'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '0', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '0', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
